# Generated by Django 2.0.2 on 2018-02-20 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_authors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
    ]
