# Generated by Django 2.0.2 on 2018-02-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20180220_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.FileField(blank=True, upload_to='author_image'),
        ),
    ]
